### ISSUE TITLE
Email templates feature requests

### ISSUE THREAD

**Issue by desoca** [Zimbra-Community/adopted#19]
Email templates is a good zimlet that is missing a couple features to make it totally usable for me:
1. the from setting is not set/saved by the template when participants are included
2. when the template is selected there should be an option to replace all text in new or current email

**Comment by barrydegraaff** [comment]
@desoca sorry, we have to work hard avoiding (regression) bugs, so adding the requested features are not on my to-do now.

Maybe if you'd consider a donation, I will be able to fix this.

Thanks
