### ISSUE TITLE
Email templates: not loading .properties file

### ISSUE THREAD

**Issue by rmontagud** [Zimbra-Community/adopted#20]
I'm testing email templates and it seems it's not loading the .properties file because when I load the mail interface I see only the language placeholders.

I'm loading the zimlet using the _dev folder if it's something to be noticed.

**Comment by dploeger** [comment]
@rmontagud Anything new on this one?

**Comment by rmontagud** [comment]
Nothing on this, deploying the zimlet works so i just assumed that's some problem on Zimbra
