### ISSUE TITLE
release new version on zimbra gallery

### ISSUE THREAD

**Issue by cassioac** [Zimbra-Community/adopted#22]
First of all thank you for this great extension.

Now a lot of people (including me) were looking for the new updated version for 8.5.x/8.6 on gallery.zimbra and may not be finding it here, is there any reason not to releasing it there?

Best Regards,

Cassio

**Comment by dploeger** [comment]
Done:

http://gallery.zimbra.com/type/zimlet/archive-adopted
http://gallery.zimbra.com/type/zimlet/attachment-alert-adopted
http://gallery.zimbra.com/type/zimlet/coloured-emails-plus-adopted
http://gallery.zimbra.com/type/zimlet/email-templates-adopted
http://gallery.zimbra.com/type/zimlet/news-and-events-sidebar-adopted
http://gallery.zimbra.com/type/zimlet/sticky-notes-adopted

Also dropped a note into the zimlet forum.
