### ISSUE TITLE
[Archive zimlet] key or keystroke to archive.

### ISSUE THREAD

**Issue by JocelynDelalande** [Zimbra-Community/adopted#23]
Would be appreciable to have some keybinding to do Archive action on current displayed thread or selected thread.

**Comment by dploeger** [comment]
That is already available (though it is not displayed in Zimbra's shortcut window due to missing features from Zimbra there).

The shortcut should be <Ctrl>-<Alt>-A

**Comment by JocelynDelalande** [comment]
@dploeger Thanks for answer, but what do you mean "--A"

hitting twice "-" and once "A" do not seem to work (but I'm not at last master).

**Comment by dploeger** [comment]
Argh, sorry. Github thought, my keystrokes were invalid tags. I meant

Ctrl-Shift-A

**Comment by JocelynDelalande** [comment]
> Argh, sorry. Github thought, my keystrokes were invalid tags. I meant
> 
> Ctrl-Shift-A

Thanks for the fix :)

Unfortunately, I the keystroke both on Chrome and Firefox, it's doing
nothing, 
I'm using a Debian GNU/Linux system, if it may help.

**Comment by dploeger** [comment]
Sorry, the correct combination is

Ctrl-Alt-A

**Comment by JocelynDelalande** [comment]
Do not work, neither,

Tested on Fx and Chrome, Debian GNU/Linux system.

**Comment by dploeger** [comment]
Hmm...Yeah, well, the shortcut system for Zimbra is kinda awkward. (see my [blog post](http://dennis.dieploegers.de/universal-and-working-method-for-handling-keyboard-shortcuts-in-zimbra-zimlets/) about it)

I don't have a Linux workstation available here. I can confirm it working on Mac OS 10.10.2 / Chrome 40.0.2214.111 (64 bit).

I'll reopen the ticket, but cannot currently fix it. Any volunteers? :)

**Comment by barrydegraaff** [comment]
@JocelynDelalande sorry the next reply took this long.

It looks like CTRL+ALT+A works, but NOT in case of multiple selections that include conversations,
select 1 single message -> works
select multiple messages, w/o conversations -> works
select 1 single conversation -> works
select multiple conversations -> fail

So probably, setting your mailview to By Message, will work-around this issue.

I will look and see if I can fix this.

**Comment by barrydegraaff** [comment]
Looking deeper into this, it looks like, the keyboard shortcut is indeed not reliable.

Pushing the Archive button in the interface appears to always work

**Comment by dploeger** [comment]
The shortcut and tab management in the current Zimbra implementation sucks as hell. (Have a look at my blogposts about the topic - http://dennis.dieploegers.de/tag/shortcut/) Maybe there's still something wrong.

**Comment by barrydegraaff** [comment]
Yeah, I agree that sucks, it looks like it is half of the problem.

It looks like something is wrong here:
CcsArchive.prototype.loadConvsAndContinue

I first thought it was the conversation view again, but may as well be some internal attribute that is different in 8.6.... it is not an easy bug

**Comment by barrydegraaff** [comment]
Looks like, if a message is viewed by the user, then selected and archived, it works (multiselect)

If a selected message has not been viewed before, then we get an error:
soapDoc.getMethod is not a function ZmBatchCommand.run

**Comment by barrydegraaff** [comment]
Yep thats it, item.msgs is not undefined for messages not previously viewed by the user.

CcsArchive.prototype.loadConvsAndContinue = function(selectedEmails) {
    var batchCmd = new ZmBatchCommand(true);
    
    var num = selectedEmails.length;    
    for ( var i = 0; i < num; i++) {
        var item = selectedEmails[i];
        console.log('a');
        console.log(ZmId.ITEM_CONV);
        console.log('b');
        console.log(item.type);
        console.log('c');
        console.log(item.msgs);

Would show:
CONV, CONV, undefined     if not viewed   and
CONV, CONV, ZmMailList   when viewed

**Comment by dploeger** [comment]
Ah, you'll probably have to issue item.load asynchronously first to get the .msgs-array.

**Comment by barrydegraaff** [comment]
Yep, adding  item.getFirstHotMsg() seems to work around the issue

        if (ZmId.ITEM_CONV === item.type && !item.msgs) {
            item.getFirstHotMsg();

**Comment by barrydegraaff** [comment]
Though not always :-p

**Comment by barrydegraaff** [comment]
@dploeger if you have an example you can share, that would be appreciated

**Comment by dploeger** [comment]
I think, you should use [ZmConv#loadMsgs](https://files.zimbra.com/docs/zimlet/zcs/8.6.0/jsapi-zimbra-doc/symbols/ZmConv.html#loadMsgs) here. It should load all missing messages and carry on with a callback.

There seems to be a (probably not working, because of the missing callback) call here: https://github.com/Zimbra-Community/adopted/blob/master/ca_uoguelph_ccs_archive/ca_uoguelph_ccs_archive.js#L608

**Comment by barrydegraaff** [comment]
I was thinking since batchCmd is defined, the code would use the callback from 
batchCmd.run(new AjxCallback(this, this.archiveSelectedEmails, [{selectedEmails: selectedEmails, convLoaded: true}]));

**Comment by dploeger** [comment]
Sorry. Yes, you're right. It does that. I was too fast. :)

**Comment by dploeger** [comment]
Which LOC is actually failing here?

**Comment by barrydegraaff** [comment]
https://github.com/Zimbra-Community/adopted/blob/master/ca_uoguelph_ccs_archive/ca_uoguelph_ccs_archive.js#L615

soapDoc.getMethod is not a function ZmBatchCommand.run

**Comment by barrydegraaff** [comment]
Looking at the documentation:
https://files.zimbra.com/docs/zimlet/zcs/8.6.0/jsapi-zimbra-doc/symbols/ZmBatchCommand.html
What this zimlet does, it not really in there

Looking here....
https://files.zimbra.com/docs/zimlet/zcs/8.6.0/jsapi-zimbra-doc/symbols/ZmConv.html
At some point this Zimlet worked, cause of compatible objects... but not sure if it was intended this way.

**Comment by barrydegraaff** [comment]
This method supports ZmZimletBase::getMsgsForConv... what is that a Christmas present?

**Comment by barrydegraaff** [comment]
CcsArchive.prototype.loadConvsAndContinue = function(selectedEmails) {
             var num = selectedEmails.length;    
             for ( var i = 0; i < num; i++) {
                 var item = selectedEmails[i];
                 if (ZmId.ITEM_CONV === item.type && !item.msgs) {
                     var ajxCallback = new AjxCallback(this, this.archiveSelectedEmails, [{selectedEmails: selectedEmails, convLoaded: true}])
                     this.getMsgsForConv( ajxCallback, item );
                 }
             }
             return true;
         };


has a few issues, but seems to work

**Comment by dploeger** [comment]
Okay. Although the BatchCommand is a bit nicer, as it encloses multiple requests (which could happen for a conversation) into one request.

**Comment by barrydegraaff** [comment]
@JocelynDelalande if you are still here, can you test:
https://github.com/Zimbra-Community/adopted/raw/master/ca_uoguelph_ccs_archive/ca_uoguelph_ccs_archive.zip
