### ISSUE TITLE
Sticky Notes doesn't work on contacts

### ISSUE THREAD

**Issue by dploeger** [Zimbra-Community/adopted#25]
As Paul Kopacz reported, the sticky notes zimlet doesn't work in the contacts application. He mentioned version 8.0.9 and I can confirm that in 8.6. The problem is in the stickynotes.js:359. The "currentView" of the contacts-controller doesn't have a "getSelection"-method. We need to call "getListView().getSelection()" on the currentView to achieve the same results.

**Comment by barrydegraaff** [comment]
Could you please test the new version, 
https://www.zimbra.org/extend/items/view/sticky-notes-adopted-

Thanks!!
