### ISSUE TITLE
Email Templates not working properly in 8.6

### ISSUE THREAD

**Issue by smsjustin** [Zimbra-Community/adopted#26]
Hi. 

Thanks for getting this working. It is a benefit at one site where we're running 8.0. However, at another site we're running 8.6 and it's having problems. 

The zimlet deploys ok and I can set a template folder, but when I save a template it saves to Drafts and is not available through the Template button.

If I send an email to myself I can drag it from Sent or Inbox to the templates folder and then it becomes selectable from the Templates button in a new email. But after selecting the template, no text is inserted into the email body or subject.

Thanks. Justin

**Comment by dploeger** [comment]
That's strange. We're running on 8.6 here and have no problems. Could you please run Zimbra in the development mode (by adding "?dev=1" to the Zimbra URL), open up something like the Chrome Developer Tools or Firebug and have a look at the console, if there are errors reported when you're trying to save a template or use one?

**Comment by barrydegraaff** [comment]
This is probably related to (see related bugs):
https://bugzilla.zimbra.com/show_bug.cgi?id=98098

**Comment by barrydegraaff** [comment]
At this point it looks like templates Zimlet is pretty broken

**Comment by barrydegraaff** [comment]
Templates gets duplicated upon testing, when sending, the template is moved away from the templates folder...

**Comment by barrydegraaff** [comment]
And at times the zimlet cannot find the template anymore, because headers are stripped of by bugs in 8.6.

Adding a message to the gallery:
*** THIS ZIMLET DOES NOT WORK IN 8.6 *** https://bugzilla.zimbra.com/show_bug.cgi?id=98098 And it probably never will, it either needs to be fixed for 8.7 OR rewritten not to used the drafts feature in Zimbra.

https://www.zimbra.org/extend/items/view/email-templates-adopted-

**Comment by barrydegraaff** [comment]
Maybe this Zimlet is upstream in 8.7:
https://bugzilla.zimbra.com/show_bug.cgi?id=96087#c1

**Comment by barrydegraaff** [comment]
Related
https://bugzilla.zimbra.com/show_bug.cgi?id=95864 
https://bugzilla.zimbra.com/show_bug.cgi?id=96087 
https://bugzilla.zimbra.com/show_bug.cgi?id=100402

**Comment by barrydegraaff** [comment]
https://bugzilla.zimbra.com/show_bug.cgi?id=100402#c7

**Comment by barrydegraaff** [comment]
@smsjustin @dploeger Good news, email templates Zimlet is working again! 

Verified against zcs-8.7.0_BETA2_1544.RHEL7_64.20160225120105

**Comment by barrydegraaff** [comment]
Closing this issue, as it works in 8.7.

Also the zimlet has been moved to:
https://github.com/Zimbra-Community/com_zimbra_emailtemplates
https://www.zimbra.org/extend/items/view/zimbra-email-templates
