### ISSUE TITLE
EMail Archive is not working properly

### ISSUE THREAD

**Issue by mammut47** [Zimbra-Community/adopted#27]
Menu "Auto-Archive" shows wrong characters. See attached Image.
Its not possible to choose any Entry in Drop-Down Box for "Archive after" and "Older as".
![2015-04-21 11_32_09-zimbra_ posteingang 28](https://cloud.githubusercontent.com/assets/12047148/7249466/dd68a7c4-e81a-11e4-90ea-2ec40b6e05c9.png)
If i choose "Archive by Month" daily every time the Archive folder is created new with a new number at the End. 
![2015-04-21 11_41_27-zimbra_ posteingang 1](https://cloud.githubusercontent.com/assets/12047148/7249567/6dcb5dc0-e81b-11e4-844b-069c66c26647.png)
Its not possible to Archive daily in Zimbra folders

**Comment by dploeger** [comment]
The first one is a wrong usage of the properties. I will correct that.

About the second thing: What version of Zimbra are you using?

**Comment by dploeger** [comment]
The first problem was corrected in 6d71a2d8d61308a3bf96154e868677125f2e4a2f

**Comment by dploeger** [comment]
@mammut47 Anything new on this?

**Comment by barrydegraaff** [comment]
@mammut47 have not been able to reproduce on Zimbra 8.6 p4.

If you still have this issue, please let us know.

**Comment by mammut47** [comment]
I tried the newest Version. Same Problem.

**Comment by barrydegraaff** [comment]
@mammut47 I have a few other bugs in the Archive Zimlet, that I will try and fix in the next week... if the issue remains then, I will ask more details.

**Comment by mammut47** [comment]
@barrydegraaff thank you for fast reply. In the last Week of this year i have time to check.

**Comment by barrydegraaff** [comment]
@mammut47 I see you use German translation, that is actually the only translated language... so *maybe* there is a bug there.

Can you try the new test version:
https://github.com/Zimbra-Community/adopted/raw/master/ca_uoguelph_ccs_archive/ca_uoguelph_ccs_archive.zip

A quick test, please test in english first THEN german, if the german does not work, I suggest dropping some parts of the translation.

Please let me know

**Comment by mammut47** [comment]
Yes! Now its all korrekt.

**Comment by barrydegraaff** [comment]
OK, you can help by leaving a review here:

  
  


https://www.zimbra.org/extend/items/view/archive-adopted-

**Comment by mammut47** [comment]
done :-) 
Many thanks for your help
