### ISSUE TITLE
Email Templates Error in 8.6

### ISSUE THREAD

**Issue by hbeezim** [Zimbra-Community/adopted#30]
We've got an issue when we try to insert body from our template email.
Chrome console raise this error : Uncaught ReferenceError: DwtHtmlEditor is not defined
We believe this is related to this : https://github.com/irontec/zsugar/issues/8
Did we miss something or it's a legitimate bug ?

Regards
Hadrien

**Comment by dploeger** [comment]
Which ZCS version are you on?

**Comment by barrydegraaff** [comment]
That usually is a cache issue. Or you maybe try to work with the Zimlet, while the web interface is not done loading.

I have not been able to reproduce this bugs, but some others are still in Templates code.
