### ISSUE TITLE
com_zimbra_stickynotes in Zimbra 8.6

### ISSUE THREAD

**Issue by cognicom** [Zimbra-Community/adopted#31]
Call me an idiot if you will, but I've just spent the past three hours trying to get the (apparently v8+ compatible) Sticky Notes zimlet to work with Zimbra 8.6 (FOSS/OSE version).

It deploys fine, but no matter what I do, the sticky note button won't appear in the user's toolbar on the webmail interface. I've tried both "enabled" and "mandatory" settings for it from the admin side, and have used several different browsers (FF, Chrome, even IE) from different computers with no difference.

One thing I do note is that each time I log in to webmail and click on the zimlet, the "enable zimlet" box is blank, but when I click it (expecting it to reload the browser window as it promises), nothing happens. Also, although Sticky Notes appears in the "Zimlets" section of the mail interface, it doesn't appear under Zimlets on the user preferences page.

Has compatibility been proven with Zimbra 8.6 (meaning I've gone crazy), or is this something still being worked on?

Thanks.

**Comment by dploeger** [comment]
I can confirm the compatibility on 8.6 (I use it on ZCS 8.6).

Could you try to start the web ui in development mode (by adding ?dev=1 to the URL) and start the Chrome development tools to see, if any error is reported when you try to enable the zimlet?

Thanks.

**Comment by MattMencel** [comment]
@cognicom I had a similar issue.  It was because the old version of the zimlet was already deployed on the mailboxes.  Once I re-deployed the zimlet and made sure to re-enable the new one in each COS...then flushed cache on the COS and zimlet...it all worked for me.

We're running 8.6 P3.

**Comment by barrydegraaff** [comment]
Try as zimbra user : zmcontrol restart

And flush your browser cache, seems to work fine on 8.6 p4

**Comment by barrydegraaff** [comment]
There is a new version, please test:
https://www.zimbra.org/extend/items/view/sticky-notes-adopted-
