### ISSUE TITLE
License blocks outdated: Zimbra Public License?

### ISSUE THREAD

**Issue by barrydegraaff** [Zimbra-Community/adopted#33]
That one is no longer up-to-date, according to:
https://blog.zimbra.com/2014/06/osi-licenses-zimbra-collaboration-open-source-edition/

I know, naggy, but I prefer free software... so if we can move it to something better than ZPL,
that would be nice.

**Comment by barrydegraaff** [comment]
10:08:37 PM - barrydg: So the code I am talking about is the attachment-alert
10:08:57 PM - barrydg: It is not a  very impressive work..... and with ZPL it is open-source
10:08:58 PM - barrydg: BUT
10:09:12 PM - barrydg: free software would be better.
10:09:39 PM - barrydg: In this case it would not matter in practice, since it can only live inside zimbra
10:10:05 PM - barrydg: Next time there is an interesting piece of software, and then it cant be used outside of zimbra, because no one
10:10:12 PM - barrydg: knows how to update the license

**Comment by dploeger** [comment]
That is a good idea. I think, I'll change the license to the MIT-license. That's the usual license I use for my other projects.

**Comment by barrydegraaff** [comment]
Why not use GPLv3?

**Comment by barrydegraaff** [comment]
Oh wait. MIT is easier to include, it sure is better than MPL.
