### ISSUE TITLE
com_zimbra_stickynotes - Portuguese_PT Translation

### ISSUE THREAD

**Issue by ruisimoes** [Zimbra-Community/adopted#35]
# 
# ***** BEGIN LICENSE BLOCK *****
# Zimbra Collaboration Suite Zimlets
# Copyright (C) 2006, 2007, 2009, 2010 Zimbra, Inc.
# 
# The contents of this file are subject to the Zimbra Public License
# Version 1.3 ("License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://www.zimbra.com/license.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
# ***** END LICENSE BLOCK *****
#

#
# Zimlet messages
#
sn_label=StickyNotes
sn_tooltip = Adicionar nota a e-mails
sn_EmailsWithStickyNotes=E-mails com StickyNotes
sn_notesSaved=StickyNotes Guardado
sn_preferences=Preferencias
sn_addToolbarButton=Adicionar botao do StickyNotes a barra principal
sn_enableStickyNotesZimlet=Ativar o StickyNotes
sn_notes=Notes: Alterar as preferencias abaixo refresca o browser

**Comment by barrydegraaff** [comment]
Could you please verify, and test the updated version here:

https://www.zimbra.org/extend/items/view/sticky-notes-adopted-

Thanks
