### ISSUE TITLE
Documentation for the Archive Zimlet?

### ISSUE THREAD

**Issue by MattMencel** [Zimbra-Community/adopted#37]
Is there documentation anywhere for the archive zimlet?  I've experimented with it, but was hoping to provide some written docs to my support people for it.  I don't want to reinvent the wheel if it's already available somewhere.

Thanks,
Matt

**Comment by barrydegraaff** [comment]
@MattMencel  I guess it is not here, it would be very much appreciated if you can write the documentation.

If you provide it in static HTML page, I will include it in the Zimlet. Thanks
