### ISSUE TITLE
 adopted/ca_uoguelph_ccs_sidebar/ does not show any event from "today"

### ISSUE THREAD

**Issue by mammut47** [Zimbra-Community/adopted#38]
We are using "Zimbra 8.6.0_GA_1182 (build 20150907121026)"
Today is not filled with content from the calendar.
Only "Tomorrow" and "soon" (demnächst)

**Comment by barrydegraaff** [comment]
It does work here, on p4.

Again, try in english UI language, and on the server: zmprov fc all and flush your browser and try again.

**Comment by mammut47** [comment]
After switching to english UI language and checking the "today" is filled. And back switching to german language -> today remains filled.
I will watch that for a while. I hope this solved the problem.
Thank you very much.
And a happy new year

**Comment by mammut47** [comment]
Switching language does not help. Recurring events are not displayed in "today". Only recurring Events are not displayed. Single events are displayed.
